config/routes.rb
Rails.application.routes.draw do
 
  resources :activities, only: [:index]

  get 'profiles/show'

 
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'register',  to: "devise/registrations#new", as: :register
    get 'login',  to: "devise/sessions#new", as: :login
    get 'logout',  to: "devise/sessions#destroy", as: :logout
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    resources :comments, module: :statuses
  end
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: "profile"
  
  scope ":profile_name" do
    resources :albums do
      resources :comments, module: :albums
      resources :pictures do
        resources :comments, module: :pictures
      end
    end
  end 


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@statuses = @user.statuses.order("created_at desc").all
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="row">
	<div class="col-md-3">
	    <%= link_to image_tag(@user.avatar.url(:small)), profile_path(@user) %>
	</div>
	<div class="col-md-6">
		<h3><%= @user.full_name %></h3>
		<% if current_user != @user %>
			<span id="friend-status">
				<% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
					<%= link_to "Edit Friendship", edit_user_friendship_path(friend_id: @user), class: "btn btn-default" %>
				<% else %>
					<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: "btn btn-default", id: "add-friendship", data: {friend_id: @user.to_param } %>
				<% end %>
			</span>
		<% end %>
	</div>
</div>


<ul class="nav nav-tabs">
	<li class="state"><%= link_to "Albums", albums_path(@user), class: "btn"  %></li>
</ul>

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="status">
				<div class="row">
					<div class="col-md-1">
						<%= link_to image_tag(status.user.avatar.url(:thumb)), profile_path(status.user.profile_name) %>
					</div>
					<div class="col-md-11">
						<p class="name"><%= status.user.full_name %></p>
						<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
						<% if current_user == status.user %>
		                  	<span class="admin">
		                    	<%= link_to "Edit", edit_status_path(status) %> |
		                    	<%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} %>
		                  </span>
	                  	<% end %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<p class="content"><%= status.content %></p>
						<% if status.document && status.document.file? %>
							<div>
	                    		<span class="label label-info">File</span>
	                    		<%= link_to status.document.file_file_name, status.document.file.url %>
	                    	</div>
	                  	<% end %>
					</div>
				</div>
				<div class="row">
		            <div class="col-md-4">
		              <%= render partial: "comments/comments", locals: {commentable: status} %>
		              <%= render partial: "comments/form", locals: {commentable: status} %>
		            </div>
	          </div>
		</div>
	<% end %>
<% end %>