config/routes.rb
Rails.application.routes.draw do
 
  resources :activities, only: [:index]

  get 'profiles/show'

 
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'register',  to: "devise/registrations#new", as: :register
    get 'login',  to: "devise/sessions#new", as: :login
    get 'logout',  to: "devise/sessions#destroy", as: :logout
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    resources :comments, module: :statuses
  end
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: "profile"
  
  scope ":profile_name" do
    resources :albums do
      resources :comments, module: :albums
      resources :pictures do
        resources :comments, module: :pictures
      end
    end
  end 


end

app/controllers/statuses/comments_controller.rb
class Statuses::CommentsController < CommentsController
	before_action :set_commentable

	private

		def set_commentable
			@commentable = Status.find(params[:status_id])
		end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  before_filter :is_signed_in?
  
  # GET /statuses
  def index
    @statuses = Status.order("created_at desc").all
  end

  # GET /statuses/1
  def show
    @status = Status.find_by_id(params[:id])
  end

  # GET /statuses/new
  def new
    @status = current_user.statuses.new
    @status.build_document
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        current_user.create_activity(@status, "created")
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  def update
    respond_to do |format|
      if @status.update(status_params)
        current_user.create_activity(@status, "updated")
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  def destroy
    @status.destroy
    respond_to do |format|
      current_user.create_activity(@status, "deleted")
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def is_signed_in?
    if !signed_in?
      redirect_to login_path, notice: "You must be logged in to access that page"
    end
  end

  private
    
    def set_status
      @status = current_user.statuses.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:content, :user_id, document_attributes: [:file])
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= simple_form_for(@status, html: { class: 'form-vertical', multipart: true }) do |f| %>
      <% if @status.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

          <ul>
          <% @status.errors.full_messages.each do |message| %>
            <li><%=message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.input :content %>
      <%= f.fields_for :document do |document_fields| %>
        <% if document_fields.object.file? %>
          <div class="control-group">
            <label class="control-label">Current file</label>
            <div class="controls">
              <%= link_to document_fields.object.file_file_name, document_fields.object.file.url %>
            </div>
          </div>
          <%= document_fields.input :remove_attachment, as: :boolean, label: "Remove file" %>
        <% end %>
        <%= document_fields.input :file, as: :file %>
      <% end %>
      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
    <% end %>
    </div>
</div>

app/views/statuses/edit.html.erb
<h3>Editing Status</h3>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-12">
          <%= link_to "Post a New Status", new_status_path, class: "btn btn-success"%>
      </div>
    </div>

     <% @statuses.each do |status| %>
      <div class="status">
            <% if !current_user.has_blocked(status.user)%>
            <div class="row">
                <div class="col-md-1">
                 <%= link_to image_tag(status.user.avatar.url(:thumb)), profile_path(status.user.profile_name) %>
                </div>
                <div class="col-md-11">
                  <p class="name"><%= status.user.full_name %></p>
                   <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
                   <% if current_user == status.user %>
                    <span class="admin">
                      <%= link_to "Edit", edit_status_path(status) %> |
                      <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} %>
                    </span>
                  <% end %>
                </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <p class="content"><%= status.content %></p>
                <% if status.document && status.document.file? %>
                  <div>
                    <span class="label label-info">File</span>
                    <%= link_to status.document.file_file_name, status.document.file.url %>
                  </div>
                <% end %>
              </div>
            </div>  
            <% end %>
            <div class="row">
              <div class="col-md-4">
                <%= render partial: "comments/comments", locals: {commentable: status} %>
                <%= render partial: "comments/form", locals: {commentable: status} %>
              </div>
            </div>
      </div>
    <% end %>
</div>

app/views/statuses/new.html.erb
<h3>New Status</h3>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<% if @status %>
	<p>
	  <b>Name: </b>
	  <%= @status.user.full_name %>
	</p>

	<p>
	  <b>Content:</b>
	  <%= @status.content %>
	</p>
	<% if @status.document && @status.document.file? %>
		<span class="label label-info">File</span>
		<%= link_to @status.document.file_file_name, @status.document.file.url %>
		<hr />

	<% end %>

	<%= link_to 'Edit', edit_status_path(@status) %> |
	<%= link_to 'Back', statuses_path %>
<% else %>
	<div class="alert alert-danger">
		<p>Status not found.</p>
	</div>
<% end %>