config/routes.rb
Rails.application.routes.draw do
 
  resources :activities, only: [:index]

  get 'profiles/show'

 
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'register',  to: "devise/registrations#new", as: :register
    get 'login',  to: "devise/sessions#new", as: :login
    get 'logout',  to: "devise/sessions#destroy", as: :logout
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    resources :comments, module: :statuses
  end
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: "profile"
  
  scope ":profile_name" do
    resources :albums do
      resources :comments, module: :albums
      resources :pictures do
        resources :comments, module: :pictures
      end
    end
  end 


end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  belongs_to :user

  has_attached_file :asset, styles: {
    large: "800x800#", medium: "300x200#", small: "260x180#", thumb: "80x80#"
  }
  
  validates_attachment :asset,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  has_many :comments, as: :commentable
end

app/controllers/pictures/comments_controller.rb
class Pictures::CommentsController < CommentsController
	before_action :set_commentable

	private

		def set_commentable
			@commentable = Picture.find(params[:picture_id])
		end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :find_user
  before_filter :find_album
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_filter :add_breadcrumbs
 
  def index
    @pictures = @album.pictures.all
  end

  # GET /pictures/1
  def show
    add_breadcrumb @picture.caption
  end

  # GET /pictures/new
  def new
    @picture = @album.pictures.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  def create
    @picture = @album.pictures.new(picture_params)
    @picture.user = current_user
    respond_to do |format|
      if @picture.save
        current_user.create_activity(@picture, "created")
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        current_user.create_activity(@picture, "created")
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  def destroy
    @picture.destroy
    respond_to do |format|
      current_user.create_activity(@status, "deleted")
      format.html { redirect_to album_pictures_url(@album), notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def url_options
    { profile_name: params[:profile_name] }.merge(super)
  end

  private
    
    def picture_params
      params.require(:picture).permit(:album_id, :user_id, :caption, :description, :asset)
    end

    def add_breadcrumbs
      add_breadcrumb @user.first_name, profile_path(@user)
      add_breadcrumb "Albums", albums_path
      add_breadcrumb "Pictures", album_pictures_path(@album)
    end

    def find_user
      @user = User.find_by_profile_name(params[:profile_name])
    end

    def find_album
      if signed_in? && current_user.profile_name == params[:profile_name]
        @album = current_user.albums.find(params[:album_id])
      else
        @album = @user.albums.find(params[:album_id])
      end
    end

    def set_picture
       @picture = @album.pictures.find(params[:id])
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= simple_form_for([@album, @picture]) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :asset, as: :file %>
        <% if f.object.asset? %>
    	    <div class="control-group">
    	    	<label class="control-label">Current asset</label>
    	    	<div class="controls">
    	      		<%= image_tag f.object.asset.url(:small)%>
    	      	</div>
    	     </div>
        <% end %>
        <%= f.input :caption %>
        <%= f.input :description %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/edit.html.erb
<h3>Editing Picture</h3>

<%= render 'form' %>

<%= link_to 'Show', album_picture_path(@album, @picture) %> |
<%= link_to 'Back', album_pictures_path(@album)%>

app/views/pictures/index.html.erb
<% if current_user == @user %>
	<div class="row">
		<div class="col-md-12">
			<%= link_to "Add Picture", new_album_picture_path(current_user, @album), class: "btn btn-success" %>
		</div>	
	</div>
<% end %>
<h4 id="album-title"><%= @album.title.capitalize %></h4>

<div class="row">
	<% @pictures.each do |picture| %>
		<div class="col-sm-6 col-md-3">
			<div class="thumbnail">
				<%= link_to image_tag(picture.asset.url(:small)), album_picture_path(@user, @album, picture) %><br />
				<div class="caption">
					<% if picture.caption? %>
						<%= picture.caption %><br />
					<% end %>
					<%= link_to "View full size", album_picture_path(@user, @album, picture) %>
					<% if current_user.pictures.include?(picture) %>
						| <%= link_to "Edit", edit_album_picture_path(@album, picture) %> |
						<%= link_to "Delete", album_picture_path(@album, picture), method: :delete,
							data: {confirm: "Are you sure?"} %>
					<% end %>
				</div>
			</div>
      		<%= render partial: "comments/comments", locals: {commentable: picture} %>
      		<%= render partial: "comments/form", locals: {commentable: picture} %>
		</div>
	<% end %>
</div>
 

app/views/pictures/new.html.erb
<h3>New Picture</h3>

<%= render 'form' %>

<%= link_to 'Back', album_pictures_path(@album) %>

app/views/pictures/show.html.erb
<h3>Viewing Picture</h3>

<div class="row">
	<div class="col-md-8">
		<%= image_tag(@picture.asset.url(:large), alt: @picture.caption, class: "img-polaroid") %>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<p><strong>Caption:</strong> <%= @picture.caption %></p>
		<p><strong>Description:</strong> <%= @picture.description %></p>
		<%= render partial: "comments/comments", locals: {commentable: @picture} %>
		<%= render partial: "comments/form", locals: {commentable: @picture} %>
		<%= link_to "Edit", edit_album_picture_path(@album, @picture) %> |
		<%= link_to "Album", album_pictures_path(@album) %>
	</div>
</div>