config/routes.rb
Rails.application.routes.draw do
 
  resources :activities, only: [:index]

  get 'profiles/show'

 
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'register',  to: "devise/registrations#new", as: :register
    get 'login',  to: "devise/sessions#new", as: :login
    get 'logout',  to: "devise/sessions#destroy", as: :logout
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  resources :statuses do
    resources :comments, module: :statuses
  end
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: "profile"
  
  scope ":profile_name" do
    resources :albums do
      resources :comments, module: :albums
      resources :pictures do
        resources :comments, module: :pictures
      end
    end
  end 


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Embook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<% if user_signed_in? %>
					<%= link_to "Embook", activities_path, class: "navbar-brand" %>
				<% else %>
					<%= link_to "Embook", root_path, class: "navbar-brand" %>
				<% end %>
				<ul class="nav navbar-nav">
					<% if user_signed_in? %>
						<li><%= link_to "All Statuses", statuses_path %></li>
						<li id="activity-feed"><%= link_to "Activity Feed", activities_path %></li>
					<% end %>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li><%= link_to "#{current_user.first_name}", profile_path(current_user) %></li>
						<li><%= link_to "Albums", albums_path(current_user) %></li>
						<li><%= link_to "Friends", user_friendships_path %></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Edit your profile", edit_user_registration_path %></li>
								<li><%= link_to "Log Out", logout_path %></li>
							</ul>
						</li>
						
					<% else %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Log In", login_path %></li>
					<% end %>
				</ul>
			</div>
	</nav>
	<div class="container">
		<%= flash_messages %>
		<%= render_breadcrumbs %>

      	<%= yield %>
	</div>

</body>

<script id="activities-template" type="text/x-handlebars-template">
  <a class="dropdown-toggle" href="#">Activity Feed ({{count}})</a>
  <ul class="dropdown-menu">
  	{{#each activities}}
  		{{activityLink}}
  	{{/each}}
  	<li class="divider"></li>
  	<li><a href="{{activityFeedLink}}">Activity Feed</a></li>
  </ul>
</script>

</html>